### ISSUE TITLE
Support Cyrillic labels 

### ISSUE THREAD

**Issue by kumov** [pattern-x/gemini-viewer-examples#91]
How to make Cyrillic labels display correctly when viewing drawings in DWF format? 
There are many drawings in Russian, but they are not displayed properly, only numbers are visible.

**Comment by kumov** [comment]
![image](https://github.com/pattern-x/gemini-viewer-examples/assets/119734016/1c392f65-1a1d-4120-b19b-76aa8e9ad462)

**Comment by pattern-x** [comment]
Hi kumov,

It is because it doesn't load proper font files before loading the dxf. The example page [empty_dxf_project.html](https://github.com/pattern-x/gemini-viewer-examples/blob/main/public/demo/empty_dxf_project.html) will load following two font files. You can try to load your font files in your example page. 
![image](https://github.com/pattern-x/gemini-viewer-examples/assets/93636579/fe07bcac-759c-43ee-b050-4debf231066b)

- git clone this example repo
- Find you could find your shx file from "C:\Program Files\Autodesk\AutoCAD 2020\Fonts\". Then put them to under public/demo/three/fonts/
- Edit your example page (empty_dxf_project.html, etc.) to load your font files.
- Then load your dxf

**Comment by kumov** [comment]
I tried adding my own fonts that are used in the drawing, but it didn't yield positive results.

**Comment by yanzexuan1** [comment]
Can you share the dxf and fonts?

**Comment by kumov** [comment]
dxf:
https://drive.google.com/file/d/1JFhZCAdKQo0c78NrDv8YmFmqKAYaRABS/view?usp=drive_link

gost.shx:
https://drive.google.com/file/d/1gOfER3OtUpGjY5oChixyuIlRQL7vs7lN/view?usp=sharing

![image](https://github.com/pattern-x/gemini-viewer-examples/assets/119734016/21da86e1-1094-4890-b92e-d50889b0ae9e)

![image](https://github.com/pattern-x/gemini-viewer-examples/assets/119734016/3c31274b-9e93-46af-b192-67d0b7d9762f)

**Comment by yanzexuan1** [comment]
Thanks for the example files. Please try to use typeface rather than shx, I tried, it works fine. 
```
const fontFiles = ["three/fonts/Microsoft_YaHei_Regular.typeface.json"];
```

![image](https://github.com/pattern-x/gemini-viewer-examples/assets/5109394/e05bade0-4205-43e5-ba72-4c6bd1f2212d)
